import { Metadata } from 'next'
import PageClient from './components/pageClient'

const Panorama = () => {
  return <PageClient />
}

export const metadata: Metadata = {
  title: '3D看房-Three.js',
  description: 'Generated by create next app'
}

export default Panorama
