import { Metadata } from 'next'
import PageClient from './components/pageClient'

const YjsEditor = () => {
  return <PageClient />
}

export const metadata: Metadata = {
  title: '协同文档-yjs',
  description: 'Generated by create next app'
}

export default YjsEditor
